[project]
name = "ambiguity-crops"
version = "0.1.0"
description = "Different solving strategies for an OR problem: MaxMin, MinRegret, Multi-objective, etc"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyomo==6.9.5",
]
